wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.1
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    m:
    - 1: trainer/global_step
      6:
      - 3
    python_version: 3.9.7
    start_time: 1687437840
    t:
      1:
      - 1
      - 9
      2:
      - 1
      - 5
      - 9
      3:
      - 7
      4: 3.9.7
      5: 0.12.1
      8:
      - 5
algorithm:
  desc: null
  value: FedAvg
alpha_kd:
  desc: null
  value: 0.5
batch_norm_round_0:
  desc: null
  value: false
batch_size:
  desc: null
  value: 8
centr_fda_ft_uda:
  desc: null
  value: false
clients_per_round:
  desc: null
  value: 2
clients_type:
  desc: null
  value: heterogeneous
cluster_layers:
  desc: null
  value: bn
color_jitter:
  desc: null
  value: false
count_classes_teacher_step:
  desc: null
  value: -1
cv2:
  desc: null
  value: false
device_ids:
  desc: null
  value:
  - 0
disable_batch_norm:
  desc: null
  value: false
discr_loss:
  desc: null
  value: diff2d
discr_loss_multiplier:
  desc: null
  value: 1
distinct_batch_norm:
  desc: null
  value: false
double_dataset:
  desc: null
  value: true
eval_interval:
  desc: null
  value: 2
fda_L:
  desc: null
  value: 0.01
fda_b:
  desc: null
  value: None
fda_loss:
  desc: null
  value: selftrain
fda_size:
  desc: null
  value:
  - 1024
  - 512
fedavg_bootstap:
  desc: null
  value: 0
fedprox:
  desc: null
  value: false
fedprox_mu:
  desc: null
  value: 0.01
force_k:
  desc: null
  value: 0
framework:
  desc: null
  value: federated
freezing:
  desc: null
  value: None
fw_task:
  desc: null
  value: oracle
gaussian_blur:
  desc: null
  value: false
global_aggregation_round:
  desc: null
  value: None
hnm:
  desc: null
  value: true
hp_filtered:
  desc: null
  value: false
ignore255_kdloss:
  desc: null
  value: false
ignore_train_metrics:
  desc: null
  value: false
ignore_warnings:
  desc: null
  value: true
lambda_entropy:
  desc: null
  value: 0.005
lambda_kd:
  desc: null
  value: 0.0
lambda_selftrain:
  desc: null
  value: 1
load:
  desc: null
  value: false
load_FDA:
  desc: null
  value: false
load_FDA_best:
  desc: null
  value: false
load_FDA_id:
  desc: null
  value: None
load_yaml_config:
  desc: null
  value: None
local_rank:
  desc: null
  value: 0
lr:
  desc: null
  value: 0.05
lr_decay_factor:
  desc: null
  value: None
lr_decay_step:
  desc: null
  value: None
lr_factor_server_retrain:
  desc: null
  value: 1.0
lr_fed:
  desc: null
  value: 0.005
lr_policy:
  desc: null
  value: None
lr_power:
  desc: null
  value: None
mixed_precision:
  desc: null
  value: false
mm_setting:
  desc: null
  value: second
model:
  desc: null
  value: multi_deeplabv3
momentum:
  desc: null
  value: 0.9
multiple_styles:
  desc: null
  value: false
n_clients_per_city:
  desc: null
  value: false
n_devices:
  desc: null
  value: 1
n_images_per_style:
  desc: null
  value: 1000
name:
  desc: null
  value: prova_pc
nesterov:
  desc: null
  value: false
num_classes:
  desc: null
  value: 19
num_epochs:
  desc: null
  value: 1
num_rounds:
  desc: null
  value: 5
num_source_epochs:
  desc: null
  value: None
num_source_epochs_factor_retrain:
  desc: null
  value: 1.0
num_source_rounds:
  desc: null
  value: None
num_source_steps_retrain:
  desc: null
  value: None
only_update_bn_server:
  desc: null
  value: false
optimizer:
  desc: null
  value: SGD
plot_interval:
  desc: null
  value: 10
pretrain:
  desc: null
  value: false
print_interval:
  desc: null
  value: 20
profiler_folder:
  desc: null
  value: None
quadruple_dataset:
  desc: null
  value: false
random_flip:
  desc: null
  value: false
random_seed:
  desc: null
  value: 42
repeat_phase_3:
  desc: null
  value: 4
save_clients_order:
  desc: null
  value: false
save_cluster_models:
  desc: null
  value: false
save_samples:
  desc: null
  value: 0
server_eval_interval:
  desc: null
  value: 1
server_lr:
  desc: null
  value: None
server_momentum:
  desc: null
  value: None
server_opt:
  desc: null
  value: None
server_test_interval:
  desc: null
  value: 1
silobn:
  desc: null
  value: false
source_dataset:
  desc: null
  value: ''
source_style_to_source:
  desc: null
  value: false
stop_epoch_at_step:
  desc: null
  value: -1
style_clusters_dir:
  desc: null
  value: None
style_only_train:
  desc: null
  value: false
swa_c:
  desc: null
  value: 1
swa_lr:
  desc: null
  value: 0.0001
swa_start:
  desc: null
  value: -1
swa_teacher_c:
  desc: null
  value: 1
swa_teacher_start:
  desc: null
  value: -1
target_dataset:
  desc: null
  value: cityscapes
teacher_kd_mult_factor:
  desc: null
  value: -1.0
teacher_kd_mult_step:
  desc: null
  value: 5
teacher_kd_step:
  desc: null
  value: -1
teacher_kd_upd_step:
  desc: null
  value: false
teacher_step:
  desc: null
  value: 1
teacher_upd_step:
  desc: null
  value: false
temperature:
  desc: null
  value: 0.01
test_batch_size:
  desc: null
  value: 2
test_interval:
  desc: null
  value: 10
test_only_with_global_model:
  desc: null
  value: false
test_source:
  desc: null
  value: false
total_batch_size:
  desc: null
  value: 8
train_source_round_interval:
  desc: null
  value: None
train_with_global_model:
  desc: null
  value: false
wandb_entity:
  desc: null
  value: alessandro-fella-1
wandb_id:
  desc: null
  value: 1ff3iaiz
wandb_offline:
  desc: null
  value: false
warmup_iters:
  desc: null
  value: None
weight_decay:
  desc: null
  value: 0.0
weights_lovasz:
  desc: null
  value: false
